name: carla-pythonapi-client-ci

on:
  workflow_dispatch:
    inputs:
      # PYTHON_VERSION:
      #   description: "The Python version used to build the client"
      #   required: true
      #   default: "3.10"
      #   type: choice
      #   options:
      #     - "3.9"
      #     - "3.10"
      #     - "3.11"
      #     - "3.12"
      CARLA_VERSION:
        description: "The version of Carla used for building."
        required: true
        default: "0.9.14"
        type: choice
        options:
          - "0.9.13"
          - "0.9.14"
          - "0.9.15"

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      pythons: ${{ steps.set-data.outputs.pythons }}
    steps:
      - uses: actions/checkout@v4
      - id: set-data
        working-directory: .
        run: |
          matrix=$(cat ./targets.json | jq -c)
          echo "pythons=$matrix" >> $GITHUB_OUTPUT
  build:
    needs: load-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.load-matrix.outputs.pythons) }}
    container:
      image: docker.io/library/python:${{ matrix.python-version }}-bookworm
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update && \
          apt install -y build-essential \
                         autoconf \
                         clang \
                         cmake \
                         curl \
                         git \
                         lld \
                         ninja-build \
                         rsync \
                         unzip \
                         wget \
                         python3-dev \
                         python3-setuptools \
                         python3-wheel \
                         libjpeg-dev \
                         libpng-dev \
                         libtiff5-dev \
                         libtool \
                         libxml2-dev
          python3 -m pip install distro
      - name: Clone Carla Repository
        run: |
          git clone --depth 1 -b ${{github.event.inputs.CARLA_VERSION}} https://github.com/carla-simulator/carla.git
          git config --global --add safe.directory /carla
      - name: Replace the build tool in Carla 0.9.14
        if: ${{ github.event.inputs.CARLA_VERSION != '0.9.14' }}
        run: |
          rm -rf carla/Util/BuildTools
          mkdir tmp && cd tmp
          git clone --depth 1 -b 0.9.14 https://github.com/carla-simulator/carla.git 
          cd .. && cp -r tmp/carla/Util/BuildTools carla/Util
      - name: Correct the Setup.sh script
        run: |
          sed -i 's/git reset --hard ${RECAST_COMMIT}/git checkout carla/g' carla/Util/BuildTools/Setup.sh
          sed -i '/mkdir -p \"${PWD}\/${RECAST_BASENAME}-install\/include\/recast\"/d' carla/Util/BuildTools/Setup.sh
          sed -i '/mv \"${PWD}\/${RECAST_BASENAME}-install\/include\/\"\*h/d' carla/Util/BuildTools/Setup.sh
      - name: Disable tests in CMakeLists.txt
        run: |
          sed -i 's/add_subdirectory(\"test\")/#add_subdirectory(\"test\")/g' carla/LibCarla/cmake/CMakeLists.txt
      - name: Remove the dirty label
        run: |
          sed -i 's/git describe --tags --dirty --always/git describe --tags --always/g' carla/Util/BuildTools/Environment.sh
      - name: Update distro usage
        run: |
          sed -i 's/distro\.linux_distribution()\[0\]/distro.id()/g' carla/PythonAPI/carla/setup.py
      - name: Build the Carla Python API client
        run: |
          cd carla
          make PythonAPI.3
      - name: Upload built
        uses: actions/upload-artifact@v4
        with:
          name: built-${{ matrix.python-version }}
          path: carla/PythonAPI/carla/dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download builts
        uses: actions/download-artifact@v4
        with:
          pattern: built-*
          path: dist
          merge-multiple: true
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: carla-${{github.event.inputs.CARLA_VERSION}}
          draft: true
          artifacts: dist/*
